Update skills
donle/sgs pull request #114
Opened 2021-01-12 12:52 UTC by Ho-spair

2021-01-19 13:33 UTC, donle requested changes

2021-01-19 13:33 UTC, donle commented on src/core/skills/characters/standard/tongji.ts
> +  public isAutoTrigger(): boolean {
why it's auto trigger

2021-01-19 13:33 UTC, donle commented on src/core/skills/characters/standard/tongji.ts
> +  public async beforeUse(room: Room, event: ServerEventFinder<GameEventIdentifiers.SkillUseEvent>): Promise<boolean> {
would prefer to select card by `isAvailableCard`

2021-01-19 13:33 UTC, donle commented on src/core/skills/characters/yijiang2011/sanyao.ts
> +      if (response.selectedOption === 'sanyap:handNum') {
```suggestion
      if (response.selectedOption === askForChooseEvent.options[1]) {
```

2021-01-19 13:33 UTC, donle commented on src/core/skills/characters/yijiang2011/sanyao.ts
> +    }
what's the exceptional case? Not recommend leaving unexpected cases away

2021-01-19 13:33 UTC, donle commented on src/core/skills/characters/yijiang2011/xuanfeng.ts
> +    await room.dropCards(CardMoveReason.PassiveDrop, [response.selectedCard], chooseCardEvent.toId, fromId, this.Name);
how to drop more than 1 card from the target?

2021-01-19 13:33 UTC, donle commented on src/core/skills/characters/yijiang2011/yongjin.ts
> +      return equipCardIds.length > 0;
why not checking banned equips for the incoming target?

2021-01-19 13:41 UTC, Ho-spair commented on src/core/skills/characters/standard/tongji.ts
> +  public isAutoTrigger(): boolean {
由beforeUse决定技能是否发动

2021-01-19 13:44 UTC, Ho-spair commented on src/core/skills/characters/standard/tongji.ts
> +  public async beforeUse(room: Room, event: ServerEventFinder<GameEventIdentifiers.SkillUseEvent>): Promise<boolean> {
发动者不为技能拥有者，所以无法使用

2021-01-28 15:31 UTC, donle approved these changes

2021-01-28 15:39 UTC, merged