update FaZheng
donle/sgs pull request #155
Opened 2021-02-16 14:21 UTC by Ho-spair

**以下为修改的技能：**
>【恩怨】当你受到1点伤害后，你可以令伤害来源选择一项：1.交给你一张手牌，若此牌不为红桃，你摸一张牌；2.失去1点体力。当你获得其他角色的牌后，若不少于两张，你可以令其摸一张牌。
>【眩惑】摸牌阶段结束时，你可以交给一名其他角色两张手牌，并选择另一名其他角色，前者选择一项：1.视为对后者使用一张任意【杀】或【决斗】；2.交给你所有手牌。

2021-02-19 04:08 UTC, doublebit015 requested changes

2021-02-19 04:08 UTC, doublebit015 commented on src/core/skills/characters/yijiang2011/xuanhuo.ts
> +            acard !== 'duel' ? new CardMatcher({ name: [acard] }) : new CardMatcher({ generalName: [acard] }),
acard is a specific card's name here, why you make it be a generalName in CardMatcher

2021-02-19 04:08 UTC, doublebit015 commented on src/core/skills/characters/yijiang2011/xuanhuo.ts
> +    const askForChooseEvent = EventPacker.createUncancellableEvent<GameEventIdentifiers.AskForChoosingOptionsEvent>({
it's better to simplify by using doAskForCommonly

2021-02-19 04:08 UTC, doublebit015 commented on src/core/skills/characters/yijiang2011/xuanhuo.ts
> +      for (const acard of attackCards) {
you repeat the operation for the same purpose, you can prepare all the data you need for the first time

2021-02-21 09:52 UTC, donle approved these changes

2021-03-02 17:11 UTC, merged