:Automatically show buttons
donle/sgs pull request #180
Opened 2021-07-22 16:11 UTC by xiaomo-li

1.change response buttons and automatically show.
2.let fubi's options Uncancellable.
3.delete reforge button
4.add AbortedCard's key

2021-07-26 14:42 UTC, donle requested changes

2021-07-26 14:42 UTC, donle commented on src/ui/platforms/desktop/src/pages/room/ui/dashboard/dashboard.module.css
> +    height: 55px;
use `gridLine` as a base pixel to make up element sizes & margins

2021-07-26 17:01 UTC, xiaomo-li commented on src/ui/platforms/desktop/src/pages/room/actions/base_action.ts
> +          this.getTarger();
sorry...

2021-07-30 16:46 UTC, donle approved these changes

2021-07-31 02:09 UTC, merged